import assert from 'node:assert/strict';
import test from 'node:test';
import { Window } from 'happy-dom';

const window = new Window({ url: 'https://gitlab.example/group/project/-/merge_requests/42/diffs' });
globalThis.window = window;
globalThis.document = window.document;
globalThis.HTMLElement = window.HTMLElement;
globalThis.customElements = window.customElements;
globalThis.CustomEvent = window.CustomEvent;
const { createGitLabHost, reviewDescriptor } = await import('../../src/gitlab-host/index.ts');

const review = reviewDescriptor({
  identity: {
    origin: 'https://gitlab.example', repositoryKey: 'https://gitlab.example/group/project',
    projectPath: 'group/project', mergeRequestIid: '42', headSha: 'a'.repeat(40),
  },
  refs: { baseSha: 'b'.repeat(40), startSha: 'c'.repeat(40) },
});

function fixture() {
  window.document.body.innerHTML = `
    <meta name="csrf-token" content="token">
    <div class="layout-page is-merge-request"><div class="ai-panels"><button id="not-ai">Other</button><nav><button id="ai-panel-button">AI</button></nav></div></div>
    <input data-testid="file-search" value="pkg/a.go">
    <diff-file id="rapid" data-file-data='{"old_path":"old/a.go","new_path":"pkg/a.go"}'>
      <header><span data-testid="file-title">pkg/a.go</span></header>
      <div data-testid="diff-file-warning">Generated by .gitattributes <a href="/help/user/project/merge_requests/changes#collapse-generated-files">help</a></div>
      <table><tr><td class="new_line"><a aria-label="Added line 12" href="#new_12">12</a></td><td class="line_content">call(<span id="rapid-code">Target</span>)</td></tr></table>
      <button data-click="showFullFile">Native full file</button>
    </diff-file>
    <div id="legacy" class="diff-file file-holder" data-path="pkg/worker_test.go">
      <header class="file-header"><span class="file-title-name">pkg/worker_test.go</span></header>
      <table><tr><td class="old_line"><a aria-label="Deleted line 7" href="#old_7">7</a></td><td class="line_content old"><span id="legacy-code">OldTarget</span></td></tr></table>
      <button data-click="showFullFile">Native full file</button>
    </div>
    <div id="tree-row" data-file-row title="pkg/worker_test.go">pkg/worker_test.go</div>`;
}

function boundHost() {
  const controller = new AbortController();
  const host = createGitLabHost({ origin: review.identity.origin, window, fetch: async () => new Response('{}') });
  return { controller, bound: host.connect(review, controller.signal) };
}

test('Rapid and legacy diffs produce normalized revision-bound targets and complete projections clean up', async () => {
  fixture();
  const { controller, bound } = boundHost();
  const events = bound.events(controller.signal)[Symbol.asyncIterator]();
  const { value: initial } = await events.next();
  assert.deepEqual(initial.files, [{ path: 'pkg/a.go', full: false }, { path: 'pkg/worker_test.go', full: false }]);
  const projection = {
    revision: initial.revision, enabled: true, hideGeneratedFiles: true, decorateTestFiles: true,
    fullFileControls: [{ path: 'pkg/a.go', full: false }, { path: 'pkg/worker_test.go', full: true, error: 'Unavailable' }],
    controls: [{ command: 'toggle-enabled', label: 'Turn GoLens off', pressed: true }],
    shortcuts: [{ command: 'focus-file-search', key: 'p', ctrlKey: true }, { command: 'toggle-bookmark', key: 'b', ctrlKey: true }],
  };
  assert.deepEqual(bound.apply(projection), { kind: 'applied' });
  assert.deepEqual(bound.apply(projection), { kind: 'unchanged' });
  assert.equal(window.document.querySelector('#rapid').hasAttribute('data-golens-generated-hidden'), true);
  assert.equal(window.document.querySelector('#legacy').hasAttribute('data-golens-test-file'), true);
  assert.equal(window.document.querySelector('#tree-row').hasAttribute('data-golens-go-test-file-row'), true);
  assert.equal(window.document.querySelector('#legacy').hasAttribute('data-golens-go-test-file-row'), false);
  assert.equal(window.document.querySelectorAll('[data-golens-full-file-control]').length, 2);
  assert.equal(window.document.querySelector('#ai-panel-button').nextElementSibling.tagName, 'GOLENS-HOST-SURFACE');
  const fullFileControl = window.document.querySelector('#rapid [data-golens-full-file-control]');
  await fullFileControl.updateComplete;
  fullFileControl.shadowRoot.querySelector('button').click();
  const { value: fullFileIntent } = await events.next();
  assert.deepEqual({ command: fullFileIntent.command, path: fullFileIntent.path }, { command: 'toggle-full-file', path: 'pkg/a.go' });
  window.document.body.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'p', ctrlKey: true, bubbles: true }));
  assert.equal((await events.next()).value.command, 'focus-file-search');
  const selection = window.getSelection();
  const range = window.document.createRange();
  const line = window.document.querySelector('#rapid .line_content');
  range.selectNodeContents(line);
  selection.removeAllRanges();
  selection.addRange(range);
  window.document.body.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'b', ctrlKey: true, bubbles: true }));
  const bookmark = (await events.next()).value.bookmark;
  assert.deepEqual(bookmark.location, { path: 'pkg/a.go', side: 'new', startLine: 12, endLine: 12 });
  assert.match(bookmark.anchor.selectionHash, /^[a-f0-9]{64}$/);
  assert.equal(bookmark.anchor.beforeHash, '');
  assert.equal(bookmark.anchor.afterHash, '');

  window.document.querySelector('#rapid-code').dispatchEvent(new window.PointerEvent('pointerover', { bubbles: true, composed: true, clientX: 210, clientY: 340 }));
  const { value: rapid } = await events.next();
  assert.deepEqual({ type: rapid.type, command: rapid.command, path: rapid.target.path, side: rapid.target.side, line: rapid.target.line, column: rapid.target.column, occurrence: rapid.target.occurrence, sha: rapid.target.source.commitSha }, {
    type: 'intent', command: 'hover-target', path: 'pkg/a.go', side: 'new', line: 12, column: 6, occurrence: 0, sha: 'a'.repeat(40),
  });
  assert.deepEqual(Object.keys(rapid).filter((key) => key === 'clientX' || key === 'clientY'), [], 'hover intents must carry no viewport pixel coordinates');
  window.document.querySelector('#rapid-code').dispatchEvent(new window.MouseEvent('click', { bubbles: true, composed: true }));
  assert.equal((await events.next()).value.command, 'select-target');
  window.document.querySelector('#legacy-code').dispatchEvent(new window.MouseEvent('click', { bubbles: true, composed: true, ctrlKey: true }));
  const { value: legacy } = await events.next();
  assert.deepEqual({ command: legacy.command, path: legacy.target.path, side: legacy.target.side, line: legacy.target.line, sha: legacy.target.source.commitSha }, {
    command: 'activate-target', path: 'pkg/worker_test.go', side: 'old', line: 7, sha: 'c'.repeat(40),
  });

  assert.deepEqual(bound.apply({ revision: initial.revision, enabled: true }), { kind: 'applied' });
  assert.equal(window.document.querySelectorAll('[data-golens-generated-hidden],[data-golens-test-file],[data-golens-go-test-file-row],[data-golens-full-file-control]').length, 0);
  controller.abort();
});

test('actions are idempotent and surfaces preserve modal focus, Escape, and teardown', async () => {
  fixture();
  const { controller, bound } = boundHost();
  const events = bound.events(controller.signal)[Symbol.asyncIterator]();
  const { value: initial } = await events.next();
  const opener = window.document.querySelector('.ai-panels button');
  opener.focus();
  bound.apply({ revision: initial.revision, enabled: true, surface: {
    kind: 'dialog', title: 'MR bookmarks', body: 'Two bookmarks', actions: [{ id: 'clear', label: 'Clear' }],
  } });
  await new Promise((resolve) => setTimeout(resolve));
  const surface = window.document.querySelector('[data-golens-active-surface]');
  const dialog = surface.shadowRoot.querySelector('[role="dialog"]');
  assert.equal(dialog.getAttribute('aria-modal'), 'true');
  assert.equal(surface.shadowRoot.activeElement?.hasAttribute('data-close'), true);
  surface.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true, composed: true }));
  assert.equal((await events.next()).value.command, 'dismiss-surface');

  const input = window.document.querySelector('[data-testid="file-search"]');
  assert.deepEqual(await bound.perform({ action: 'clear-file-search', revision: initial.revision, operationId: 'clear' }, controller.signal), { kind: 'completed' });
  assert.equal(input.value, '');
  assert.deepEqual(await bound.perform({ action: 'clear-file-search', revision: initial.revision, operationId: 'clear' }, controller.signal), { kind: 'unchanged' });

  let nativeClicks = 0;
  window.document.querySelector('[data-click="showFullFile"]').addEventListener('click', () => nativeClicks++);
  assert.deepEqual(await bound.perform({ action: 'set-full-file', revision: initial.revision, operationId: 'full', path: 'pkg/a.go', full: true }, controller.signal), { kind: 'completed' });
  assert.equal(nativeClicks, 1);

  window.document.querySelector('#rapid-code').dispatchEvent(new window.PointerEvent('pointerover', { bubbles: true, composed: true }));
  const target = (await events.next()).value.target;
  assert.deepEqual(await bound.perform({ action: 'reveal-target', revision: initial.revision, operationId: 'reveal', target }, controller.signal), { kind: 'completed' });
  assert.deepEqual(await bound.perform({ action: 'reveal-source', revision: initial.revision, operationId: 'source', source: target.source, path: target.path, line: 12 }, controller.signal), { kind: 'completed' });
  bound.apply({ revision: initial.revision, enabled: true, occurrenceLocations: [{ source: target.source, path: target.path, line: 12 }] });
  assert.equal(window.document.querySelector('#rapid tr').hasAttribute('data-golens-occurrence'), true);
  assert.deepEqual(await bound.perform({ action: 'navigate-relative', revision: initial.revision, operationId: 'occurrence', kind: 'occurrence', direction: 'next' }, controller.signal), { kind: 'completed' });
  assert.deepEqual(await bound.perform({ action: 'reveal-target', revision: initial.revision, operationId: 'forged', target: { ...target, token: 'forged' } }, controller.signal), { kind: 'unavailable', reason: 'not-rendered' });
  assert.deepEqual(await bound.perform({ action: 'set-fullscreen', revision: initial.revision, operationId: 'fullscreen', active: true }, controller.signal), { kind: 'unavailable', reason: 'unsupported' });

  const copied = [];
  Object.defineProperty(window.navigator, 'clipboard', { configurable: true, value: { async writeText(value) { copied.push(value); } } });
  assert.deepEqual(await bound.perform({ action: 'copy-source-location', revision: initial.revision, operationId: 'copy', text: 'pkg/a.go:12' }, controller.signal), { kind: 'completed' });
  assert.deepEqual(copied, ['pkg/a.go:12']);

  const opened = [];
  window.open = (...args) => { opened.push(args); return null; };
  await bound.perform({ action: 'open-destination', revision: initial.revision, operationId: 'open', destination: {
    kind: 'source', source: target.source, path: target.path, line: 12,
  } }, controller.signal);
  assert.equal(String(opened[0][0]), `https://gitlab.example/group/project/-/blob/${'a'.repeat(40)}/pkg/a.go#L12`);

  controller.abort();
  assert.equal(window.document.querySelector('[data-golens-active-surface]'), null);
  assert.equal(window.document.activeElement, opener);
});
